// THIS FILE IS AUTOGENERATED. DO NOT EDIT.

char aws_shadow_topic_get[]= "$aws/things/hommieo_afbedbfe-ea2b-49c2-a868-f2690b4afb2f/shadow/get";
char aws_shadow_topic_get_return[]= "$aws/things/hommieo_afbedbfe-ea2b-49c2-a868-f2690b4afb2f/shadow/get/accepted/raw";

char aws_shadow_topic_update[]= "$aws/things/hommieo_afbedbfe-ea2b-49c2-a868-f2690b4afb2f/shadow/update";
char aws_shadow_topic_update_return[]= "$aws/things/hommieo_afbedbfe-ea2b-49c2-a868-f2690b4afb2f/shadow/update/accepted/raw";

char aws_custom_ping[]= "hommieo/dev/hommieo_afbedbfe-ea2b-49c2-a868-f2690b4afb2f/ping";
