// THIS FILE IS AUTOGENERATED. DO NOT EDIT.

char aws_shadow_topic_get[]= "$aws/things/hommieo_9e2c0d3b-88bd-46fc-a18d-5291a3737e83/shadow/get";
char aws_shadow_topic_get_return[]= "$aws/things/hommieo_9e2c0d3b-88bd-46fc-a18d-5291a3737e83/shadow/get/accepted/raw";

char aws_shadow_topic_update[]= "$aws/things/hommieo_9e2c0d3b-88bd-46fc-a18d-5291a3737e83/shadow/update";
char aws_shadow_topic_update_return[]= "$aws/things/hommieo_9e2c0d3b-88bd-46fc-a18d-5291a3737e83/shadow/update/accepted/raw";

char aws_custom_ping[]= "hommieo/dev/hommieo_9e2c0d3b-88bd-46fc-a18d-5291a3737e83/ping";
