// THIS FILE IS AUTOGENERATED. DO NOT EDIT.

char aws_shadow_topic_get[]= "$aws/things/hommieo_8d2f25d2-6478-4536-9bc2-3fdb3da616ec/shadow/get";
char aws_shadow_topic_get_return[]= "$aws/things/hommieo_8d2f25d2-6478-4536-9bc2-3fdb3da616ec/shadow/get/accepted/raw";

char aws_shadow_topic_update[]= "$aws/things/hommieo_8d2f25d2-6478-4536-9bc2-3fdb3da616ec/shadow/update";
char aws_shadow_topic_update_return[]= "$aws/things/hommieo_8d2f25d2-6478-4536-9bc2-3fdb3da616ec/shadow/update/accepted/raw";

char aws_custom_ping[]= "hommieo/dev/hommieo_8d2f25d2-6478-4536-9bc2-3fdb3da616ec/ping";